### ISSUE TITLE
Develop PR checklist (beyond black, flake8 etc)

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#144]
Lessons learnt from @cthoyt so far:

- [ ] Ensured docstrings of all functions I touched are up to date
- [ ] Checked that my coding aligns with the @cthoyt [style guide](https://cthoyt.com/2021/09/13/beyond-linters.html)
- [ ] Ensure all my variables have meaningful names
- [ ] Consider [keyword-only arguments](https://lukeplant.me.uk/blog/posts/keyword-only-arguments-in-python/) were appropriate
- [ ] Dont add defaults in to the function definition, default to None and handle defaults inside the function
- [ ] Precompile frequently use regexes
- [ ] Use imperative mood in docstrings and always end with a period

We may want to add this checklist or a reduced or better version as a PR template as well.
